### PR TITLE
add Dockerfile

### PR DESCRIPTION
**Pull request by flier**

### CODE REVIEW

**Comment by flier** [comment]
I have created a project at docker hub, do you have interesting to maintain an official build? or I added you to that project?

**Comment by fffonion** [comment]
I'll appreciate that if you want to maintain the docker image.
And if you need to prove it to "official" just add the link of the docker image to `Readme.md` and send a PR to this repo. :smile:

**Comment by flier** [comment]
OK

Alliumcepa Triplef <notifications@github.com>于2016年3月2日周三 11:28写道：

**Comment by fffonion** [comment]
Just for an alternative for people who are concerned about disk usage, using `python:2.7-alpine` as base image is a better approach. ;-)

**Comment by flier** [comment]
Thanks for your advice, just update Dockerfile and reduce image from 200M
to 73M

https://github.com/flier/Xunlei-Fastdick/commit/1b9ee9abbe347ac80675469d4c2bf36526ecef82



Alliumcepa Triplef <notifications@github.com>于2016年3月26日周六 上午1:25写道：

**Pull request merged**
